### ISSUE TITLE
When uploading large files, it would be nice to have a progress bar or other indicator of progress

### ISSUE THREAD

**Issue by paulproteus** [mnutt/davros#18]
Steps to reproduce:

- Create a davros grain

- Use the menu to select a file and upload it to the grain

Expected behavior:

- See some indication that upload is in progress

Actual behavior:

- The only indication is that the grain size is increasing, which is an indicator, I suppose, but a very subtle one! (-:

References:

- https://www.reddit.com/r/selfhosted/comments/3v6e1n/5_open_source_selfhostable_web_apps_alternatives/

**Comment by mnutt** [comment]
Oops, this was totally intended to work, but I did a big refactoring of the uploading in the last version and it broke it. Fixed in https://github.com/mnutt/davros/commit/033ed3a2c6cce22b7ef7d7c9fa143eb2e00c974d and will get released in the next version.

Even so, the indicator is extremely minimal. I'd be curious if it's sufficient for web uploads, or if a more full-featured upload progress page listing individual uploads would be useful at some point.
