### ISSUE TITLE
[Meta] Easiest way to package a Go app for Sandstorm?

### ISSUE THREAD

**Issue by elimisteve** [mnutt/davros#31]
I'll be doing exactly this very soon.  Thanks!

**Comment by mnutt** [comment]
Setting up a go app for sandstorm shouldn't be much different from any other kind of app. I tend to use vagrant-spk so that I can develop on my mac. Vagrant-spk has 'stacks' but does not include go, since I don't think there's a consistent enough deploy strategy to need it. (at least, compared to something like php or rails) I'd use the `diy` stack.

Then, it's just a matter of modifying `setup.sh` to get the go build toolchain and then doing the build in `build.sh`. It's easiest if your app just listens on port 8000, which is what vagrant-spk expects by default.

If you run into issues or have further questions, the sandstorm-dev google group is a great place to ask them.

**Comment by elimisteve** [comment]
@mnutt Ha ha, sorry about that!  I looked at the source of Davros and https://github.com/zombiezen/filedrop at about the same time and thought Davros was written in Go, which is why I bothered asking about packaging Go apps here :-).
