### ISSUE TITLE
[Question] Is it possible to restore deleted files?

### ISSUE THREAD

**Issue by jason-riddle** [mnutt/davros#75]

**Comment by mnutt** [comment]
Unfortunately, currently no. Right now davros is basically just a pass-through to the filesystem. There's a bit of extra metadata (etag hashes) stored in hidden directories, but when a file is deleted from webdav it's deleted off the disk.

The tentative plan is to try to go straight to a versioned filesystem, so that you can restore previous versions of a file as well as undeleting it. One of the big challenges is that people are very cognizant of their sandstorm grain sizes and I want to give them maximum control over how much extra space versioning takes up.

**Comment by jason-riddle** [comment]
Makes sense. Thanks!
